#!/usr/bin/env python3
"""Render the hardware-dependent parts of the desktop configs from config.sh values.

Called by post-install.sh, which passes the config values as environment variables:
  render.py hyprland <template> <dest>   MONITORS, MONITORS_JSON, KB_LAYOUT, KB_VARIANT, CORSAIR_KEYBOARD
  render.py waybar   <template> <dest>   CPU_HWMON, GPU_DRIVER, UNDERVOLT
Warnings go to stderr; the exit status is 0 unless the template is malformed.
"""
import json
import os
import re
import sys

BLOCK_RE = re.compile(r"^-- >>> monitors.*?^-- <<< monitors\n", re.M | re.S)
PORT_RE = re.compile(r"^[A-Za-z]+(-[A-Za-z])?-\d+$")   # DP-1, HDMI-A-1, eDP-1, DVI-D-1
FALLBACK = 'hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })'


def warn(msg):
    print(f"render: {msg}", file=sys.stderr)


def parse_monitors(spec):
    """'MATCH|MODE|POSITION|SCALE|VRR' lines -> list of dicts."""
    monitors = []
    for line in spec.splitlines():
        if not line.strip():
            continue
        match, mode, position, scale, vrr = line.split("|")
        monitors.append({"match": match, "mode": mode, "position": position,
                         "scale": scale, "vrr": int(vrr)})
    return monitors


def resolve_port(match, connected):
    """Port name for MATCH: an exact port name, else a case-insensitive part of the description."""
    for m in connected:
        if m.get("name") == match:
            return m["name"]
    needle = match.lower()
    for m in connected:
        text = " ".join(str(m.get(k, "")) for k in ("description", "make", "model")).lower()
        if needle in text:
            return m["name"]
    if not connected and PORT_RE.match(match):
        return match            # not running inside Hyprland: trust an explicit port name
    return None


def lua_scale(scale):
    return '"auto"' if scale == "auto" else scale


def monitor_block(monitors, connected):
    lines = ["-- >>> monitors: generated by post-install.sh from MONITORS in config.sh"]
    found = []
    for mon in monitors:
        port = resolve_port(mon["match"], connected)
        if port is None:
            warn(f"monitor '{mon['match']}' not found (connected: "
                 f"{', '.join(m.get('name', '?') for m in connected) or 'unknown'}); "
                 "it gets Hyprland's automatic settings")
            continue
        found.append((mon, port))
    ports = [port for _, port in found]
    names = ["MAIN", "SIDE"]
    for i, port in enumerate(ports[:2]):
        lines.append(f'local {names[i]} = "{port}"')
    for i, (mon, port) in enumerate(found):
        output = names[i] if i < 2 else f'"{port}"'
        lines.append(f'hl.monitor({{ output = {output}, mode = "{mon["mode"]}", '
                     f'position = "{mon["position"]}", scale = {lua_scale(mon["scale"])}, '
                     f'vrr = {mon["vrr"]} }})')
    lines.append(FALLBACK)
    if ports:
        lines.append("")
        lines.append('hl.workspace_rule({ workspace = "1", monitor = MAIN, default = true })  -- games, editor')
        lines.append('hl.workspace_rule({ workspace = "2", monitor = MAIN })                  -- browser')
    if len(ports) > 1:
        lines.append('hl.workspace_rule({ workspace = "3", monitor = SIDE, default = true })  -- docs, chat, terminal')
    lines.append("-- <<< monitors")
    return "\n".join(lines) + "\n"


def render_hyprland(text, env):
    if not BLOCK_RE.search(text):
        sys.exit("render: hyprland template has no '-- >>> monitors' block")
    connected = json.loads(env.get("MONITORS_JSON") or "[]")
    block = monitor_block(parse_monitors(env.get("MONITORS", "")), connected)
    text = BLOCK_RE.sub(lambda _: block, text, count=1)
    text = re.sub(r'(kb_layout\s*=\s*)"[^"]*"', lambda m: f'{m.group(1)}"{env.get("KB_LAYOUT", "us")}"', text)
    text = re.sub(r'(kb_variant\s*=\s*)"[^"]*"', lambda m: f'{m.group(1)}"{env.get("KB_VARIANT", "")}"', text)
    if env.get("CORSAIR_KEYBOARD") != "yes":
        text = "".join(line for line in text.splitlines(keepends=True) if "ckb-next" not in line)
    return text


def drop_module(text, name):
    """Remove a module from every modules-* list and delete its definition line."""
    def fix_list(m):
        mods = [x for x in json.loads(m.group(2)) if x != name]
        return m.group(1) + "[" + ", ".join(json.dumps(x) for x in mods) + "]"
    text = re.sub(r'("modules-(?:left|center|right)":\s*)(\[[^\]]*\])', fix_list, text)
    return "".join(line for line in text.splitlines(keepends=True)
                   if not line.lstrip().startswith(json.dumps(name) + ":"))


def render_waybar(text, env):
    hwmon = env.get("CPU_HWMON", "")
    if hwmon:
        text = re.sub(r'("hwmon-path-abs":\s*)"[^"]*"', lambda m: m.group(1) + json.dumps(hwmon), text)
    else:
        warn("no CPU temperature sensor (k10temp/coretemp) found; removing the temperature module")
        text = drop_module(text, "temperature")
    if env.get("UNDERVOLT") != "yes":
        text = drop_module(text, "custom/cpu_voltage")
    if env.get("GPU_DRIVER") not in ("nvidia-open", "nvidia-580xx", "amd"):
        text = drop_module(text, "custom/gpu")
    return text


def main():
    if len(sys.argv) != 4 or sys.argv[1] not in ("hyprland", "waybar"):
        sys.exit(__doc__)
    kind, src, dest = sys.argv[1:]
    with open(src, encoding="utf8") as f:
        text = f.read()
    render = render_hyprland if kind == "hyprland" else render_waybar
    out = render(text, os.environ)
    with open(dest, "w", encoding="utf8") as f:
        f.write(out)


if __name__ == "__main__":
    main()
